### ISSUE TITLE
How to integrate this into ESPhome

### ISSUE THREAD

**Issue by Diegus83** [IamTheCarl/ESPHome-Frigidaire#1]
Hi!

Is this a custom component to control a Frigidaire AC via an IR emitter in ESPHome?

If that is the case how would one go about using it?

I'm just starting with ESPHome and I have a Frigidaire AC that doesn't seem to be supported by the climate_ir component.

Thanks for your help.

**Comment by IamTheCarl** [comment]
Yes, this is a custom component.

Under Home Assistant's ESPHome directory (where all your devices yaml files are located) you can create a directory called `components` and clone this repository under there (esphome/components/frigidaire). You can pull this repo any time you need to update.

Do note that I still use this thing, I just haven't needed to update it for the last two years.
